# Generated by Django 5.2.8 on 2025-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
