# Generated by Django 5.2.8 on 2025-12-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('fatculty', 'Fatculty'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
