# Generated by Django 5.2.8 on 2025-11-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('complaints', '0002_initial'),
        ('maintenance', '0002_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
