# Generated by Django 5.2.8 on 2025-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('library', 'Library Room'), ('auditorium', 'Auditorium')], default='Lecture Hall', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50, verbose_name='Room Number'),
        ),
    ]
