# Generated by Django 5.2.8 on 2025-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_room_type_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default='-', null=True),
        ),
    ]
