# Generated by Django 5.2.8 on 2025-11-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='equepment',
            new_name='equipment',
        ),
    ]
