# Generated by Django 5.2.8 on 2026-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_equepment_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('library', 'Library Room'), ('auditorium', 'Auditorium')], default='Lecture', max_length=20),
        ),
    ]
