# Generated by Django 5.2.8 on 2026-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('library', 'Library Room'), ('auditorium', 'Auditorium')], default='lecture', max_length=20),
        ),
    ]
