# Generated by Django 5.2.8 on 2026-03-02 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building_type', models.CharField(choices=[('building', 'Building'), ('cafeteria', 'Cafeteria')], default='building', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building'),
        ),
    ]
