# Generated by Django 5.2.8 on 2026-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_building_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('building', 'Building'), ('cafeteria', 'Cafeteria')], default='building', max_length=20),
        ),
    ]
