# Generated by Django 5.2.8 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_building_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('cafeteria', 'Cafeteria'), ('building', 'Building')], default='building', max_length=20),
        ),
    ]
