# Generated by Django 5.2.8 on 2026-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_alter_building_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('building', 'Academic Building'), ('administration', 'Administration Building'), ('library', 'Library Building'), ('service', 'Service Building'), ('cafeteria', 'Cafeteria')], default='building', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('library', 'Library Room'), ('auditorium', 'Auditorium'), ('other', 'Other')], default='lecture', max_length=20),
        ),
    ]
