# Generated by Django 5.2.8 on 2026-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='MaintenancePhotos/%d/%m/%y'),
        ),
    ]
