# Generated by Django 5.2.8 on 2026-02-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancerequest_photo'),
        ('rooms', '0007_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rooms.room'),
        ),
    ]
