# Generated by Django 5.2.8 on 2026-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancerequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
