# Generated by Django 5.2.8 on 2026-02-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancerequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='name',
        ),
    ]
