# Generated by Django 5.2.8 on 2026-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_maintenancerequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
