# Generated by Django 5.2.8 on 2026-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenancerequest_email_maintenancerequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
