# Generated by Django 5.2.8 on 2026-02-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_maintenancerequest_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='name',
        ),
    ]
