# Generated by Django 5.2.8 on 2026-02-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_maintenancerequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
