# Generated by Django 5.2.8 on 2026-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenancerequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='name',
        ),
    ]
