# Generated by Django 5.2.8 on 2026-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_remove_maintenancerequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='maintenance_type',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('furniture', 'Furniture Damage'), ('ac', 'Air Conditioning'), ('plumbing', 'Plumbing'), ('equipment', 'Equipment Failure'), ('network', 'Network / Internet'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('under repair', 'Under Repair'), ('fixed', 'Fixed')], default='pending', max_length=15),
        ),
    ]
