# Generated by Django 5.2.8 on 2026-02-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_maintenancerequest_maintenance_type_and_more'),
        ('rooms', '0009_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rooms.room'),
        ),
    ]
