# Generated by Django 5.2.8 on 2025-11-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='image',
            new_name='photo',
        ),
    ]
