# Generated by Django 5.2.8 on 2025-12-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_photo'),
        ('rooms', '0006_rename_equepment_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
