# Generated by Django 5.2.8 on 2025-12-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
