# Generated by Django 5.2.8 on 2026-02-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaint_classroom_alter_complaint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='student_name',
            new_name='name',
        ),
    ]
