# Generated by Django 5.2.8 on 2026-02-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_rename_student_email_complaint_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
    ]
