# Generated by Django 5.2.8 on 2025-11-17 00:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('rooms', '0006_rename_equepment_room_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('classroom', 'booking_date', 'start_time', 'user')},
        ),
    ]
