# Generated by Django 5.2.8 on 2026-02-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_email_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
