# Generated by Django 5.2.8 on 2026-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
