# Generated by Django 5.2.8 on 2026-03-03 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_is_deleted_booking_notes'),
        ('rooms', '0015_alter_building_building_type_alter_room_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_deleted', 'status', '-created_at'], name='bookings_bo_is_dele_4808eb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'is_deleted', '-created_at'], name='bookings_bo_user_id_f1b9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['classroom', 'booking_date', 'status'], name='bookings_bo_classro_548148_idx'),
        ),
    ]
